# Generated by Django 4.2 on 2024-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_outstanding_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(auto_now_add=True),
        ),
    ]
