# Generated by Django 4.2 on 2024-10-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_payment_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='storebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.storebook'),
        ),
    ]
